### ISSUE TITLE
use firefox 3dof&6dof version goto Mozilla Hubs ，interact with multiple people， The voice microphone is low

### ISSUE THREAD

**Issue by dingsing2021** [hms-ecosystem/OpenXR-SDK#19] opened 2021-11-01 07:23 UTC
Updated the problems experienced in the 3Dof version.
Enter the Mozilla Hubs space and interact with multiple people. The following problem is found:
1. Use the microphone provided by the VR Glass (on the in-line controller). The voice microphone is low,

There should be no problem with the MIC hardware that comes with the VR Glass. We tried to make a call directly with the VR Glass, and the sound was clear.

**Comment by fwei-io** [comment] 2021-11-04 15:14
@MortimerGoro please help investigate this issue, thanks.

**Comment by MortimerGoro** [comment] 2021-11-05 17:27
I looked into this issue today. I can reproduce it on any webpage using the microphone.

The problem is that gecko web engine is using the microphone from the mobile instead the one from the headset. I investigated where Gecko is initializing the device. It was not easy to find, because they are not using the AudioRecorder java code directly.

Gecko is using https://github.com/mozilla/cubeb to capture the audio. On Android there are two backends. The one used by default is OpenSL, but they haven't implemented input device selection: "Device selection is not supported in Android. The default will be used". https://searchfox.org/mozilla-central/source/media/libcubeb/src/cubeb_opensl.c#1385

I tried to switch to the AAudio backend, which has a AAudioStreamBuilder_setDeviceId method.  I called `AAudioStreamBuilder_setDeviceId` using the ID for the USB_HEADSET device got using AudioManager from java. But it still didn't work, it continued to use the default microphone from the mobile.

We need either:
- The system change the default microphone when the VR glasses are attached
- Implement device selection in cubeb, which might be quite a work. I'm not an expert on that library, so we'd need to ask some of the developers of that area

**Comment by dingsing2021** [comment] 2021-11-16 05:54
> I looked into this issue today. I can reproduce it on any webpage using the microphone.
> 
> The problem is that gecko web engine is using the microphone from the mobile instead the one from the headset. I investigated where Gecko is initializing the device. It was not easy to find, because they are not using the AudioRecorder java code directly.
> 
> Gecko is using https://github.com/mozilla/cubeb to capture the audio. On Android there are two backends. The one used by default is OpenSL, but they haven't implemented input device selection: "Device selection is not supported in Android. The default will be used". https://searchfox.org/mozilla-central/source/media/libcubeb/src/cubeb_opensl.c#1385
> 
> I tried to switch to the AAudio backend, which has a AAudioStreamBuilder_setDeviceId method. I called `AAudioStreamBuilder_setDeviceId` using the ID for the USB_HEADSET device got using AudioManager from java. But it still didn't work, it continued to use the default microphone from the mobile.
> 
> We need either:
> 
> * The system change the default microphone when the VR glasses are attached
> * Implement device selection in cubeb, which might be a lot of work. I'm not an expert on that library, so we'd need to ask some of the developers of that area

thanks,got it. We have other developers who have successfully used MICs on VR Glass, and they work well. One uses untiy and the other uses unreal.

**Comment by dingsing2021** [comment] 2021-11-16 07:34
Add some information, I hope it helps.
1. When Firefox accesses Mozilla Hubs and initiates a voice call between two people, the microphone on the VR Glass works, but the voice is small. The microphone on the phone is not directly invoked.
2. There is a developer in China who uses the agora SDK. Currently, the voice effect of the app is good.
https://www.agora.io/cn/voicecall

**Comment by fwei-io** [comment] 2021-11-17 01:22
@dingsing2021 this is most likely issue with Gecko not able to use VR Glass mic as the default. We need your developer to check Gecko API to see if it can work with OpenXR SDK to choose the correct mic source. @MortimerGoro will create an issue in Gecko project for your team to work on. We should discuss in the next meeting.

**Comment by MortimerGoro** [comment] 2021-11-19 17:46
There is already a issue created in Gecko for Android: https://github.com/mozilla-mobile/fenix/issues/16653

**Comment by fwei-io** [comment] 2022-05-05 22:44
Closing this issue and continue to track here - https://github.com/mozilla-mobile/fenix/issues/16653

**Closed by fwei-io** 2022-05-05 22:44 UTC
